GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "And another thing in defence of Blorbo",
    "author": "Blorbo",
    "url": "blog.com/blorbo_defence",
    "likes": 1
}