POST http://localhost:3001/api/patients
Content-Type: application/json

{
    "name": "Andrew Mandrew",
    "dateOfBirth": "1999-12-01",
    "ssn": "111111-111111",
    "gender": "other",
    "occupation": "Stepladder"
}

###
get http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667

###
get http://localhost:3001/api/patients/

