GET http://localhost:3001/api/persons
###
GET http://localhost:3001/api/persons/68514f9a4fdb1368359c0379
###
POST http://localhost:3001/api/persons/
Content-Type: application/json

{
    "name": "Mike Manflesh",
    "number": "0234234234"
}
###
PUT http://localhost:3001/api/persons/6852a8c9944042cfa0bc118d
Content-Type: application/json

{
    "name": "Frank Wolfman",
    "number": "2342344"
}
###
DELETE http://localhost:3001/api/persons/6852992bca659e114aeb8723
###
GET http://localhost:3001/api/persimons/

###
GET http://localhost:3001/info