GET https://fullstackopen-phonebook-backend-su3b.onrender.com/api/persons
###
POST https://fullstackopen-phonebook-backend-su3b.onrender.com/api/persons/
Content-Type: application/json

{
    "name": "Testis Testerson",
    "number": "02934820394"
}
###
DELETE https://fullstackopen-phonebook-backend-su3b.onrender.com/api/persons/65